### ISSUE TITLE
Trabalho avaliado 🫡

### ISSUE THREAD

**Issue by lucasferreira** [miguelfermo/Front-web#5]
Galerinha mais animada das minhas aulas de quarta-feira, inicio o comentário agradecendo a presença e participação em sala de aula de vocês ao longo deste semestre, espero que tenha sido proveitoso em alguma escala esses poucos encontros que passamos juntos na disciplina de Front-end, vou sentir saudades desse quinteto.

O trabalho de vocês ficou bem bacana, tema de bom de se trabalhar, a área semi-e-commerce que lida com pagamentos é sempre algo bom de explorar, ainda mais com "tema social" junto.

Achei que a ideia de dividir bem as tarefas entre os integrantes foi promissora, achei ousada a ideia de separar uma pasta de componentes para cada membro, MASSS também achei que faltou um pouco de "unidade" parece que cada um fez sua tarefa de um jeito _(não que tenha ficado ruim)_.

Apesar de não ser necessário/requisito, como vocês fizeram a ideia de ser um site de doações achei que ficou faltando funcionar "corretamente" a navegação sem login (pública) e também achei estranho a funcionalidade de logout/sair e o fato de ter que excluir o usuário para ver outras coisas não logadas.

Também acho que poderia ter algo mais detalhado sobre cada "vakinha" tipo uma página contendo numero de valores já doados e quem sabe alguma coisa de PIX mais óbvia.

Tudo que observei são detalhes, poucos afetam os requisitos/notas, porque no geral eu gostei 👊

E era isso, agradeço novamente e depois mais tarde podem conferir a nota no portal.

_p.s: a animação da tela de login ficou massa \o/_
_p.s. 2: tive bastante dificuldade de rodar o projeto de vcs no stackblitz, muitos nomes escritos errados tipo o arquivo é PageEdit.jsx e no import está `pageEdit`._

**Comment by miguelfermo** [comment]
Obrigado, Lucas! Gostou da tela de Login né.... 🔥🔥🤷🏽‍♂️🤷🏽‍♂️
